version: "3"
services:
  frontend:
    container_name: frontend
    build: ./frontend
    stdin_open: true
    volumes:
      - "./frontend:/app"
      - "./frontend/node_modules"
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
  backend:
    container_name: backend
    build: ./
    volumes:
      - ".:/app/"
      - "./node_modules"
    ports:
      - "9007:9007"
    depends_on:
      - mongo
    expose:
      - "9007"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none
